language: python
cache: pip
dist: xenial

matrix:
  include:
    - name: Check black formatting
      python: 3.7
      env: TOXENV=black
    - name: Check flake8
      python: 3.7
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37

install:
  - pip install tox

script:
  - tox
